name: contracts
version: 0.1.0.0
library:
  source-dirs: src
  exposed-modules:
    - CheckCheck.Contracts.API
    - CheckCheck.Contracts.Users
    - CheckCheck.Contracts.Users.Budget
    - CheckCheck.Contracts.Users.Contacts
    - CheckCheck.Contracts.Users.OutgoingRequests
    - CheckCheck.Contracts.Users.IncomingRequests
    - CheckCheck.Contracts.Groups
    - CheckCheck.Contracts.Receipts

  dependencies:
  - smart-primitives

  - base
  - servant
  - servant-auth
  - text
  - uuid
  - aeson
  - time

  ghc-options:
  - -Wno-partial-fields
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wredundant-constraints
